[program:set-passwords]
command=/usr/local/bin/set-passwords.sh
user=root
autostart=true
autorestart=false
startsecs=0
startretries=1
exitcodes=0
priority=2
stdout_logfile=/var/log/set-passwords.log
stderr_logfile=/var/log/set-passwords.err
stdout_logfile_maxbytes=1MB
stderr_logfile_maxbytes=1MB
